### ISSUE TITLE
[EPIC] CMP Endpoint for onboarded devices

### ISSUE THREAD

**Issue by AlexHx8472** [Trustpoint-Project/trustpoint#123]
**Introduction**
The Trustpoint shall offer an CMP Endpoint for onboarded devices.

**Acceptance Criteria**
- Make the endpoints available for the following operations and for all configured domains separately:
    - [ ] #136 
    - [ ] Job Story #x : CertificationRequest (CR)
    - [ ] Job Story #x : KeyUpdateRequest (KUR)
    - [ ] Job Story #x : PKCS#10Request (P10CR)
    - [ ] Job Story #x : RevocationRequest (RR)
    - [ ] Job Story #x : GetCaCertsRequest (CACERTS)
    - [ ] Job Story #x : GetRootUpdate (RootUpd)
    - [ ] Job Story #x : GetCrls (GetCrls)
