### ISSUE TITLE
[EPIC] Backup, restore and update mechanisms

### ISSUE THREAD

**Issue by AlexHx8472** [Trustpoint-Project/trustpoint#130]
**Introduction**
Add an appropriate backup, restore an update mechanism to the Trustpoint.

**Acceptance Criteria**
- [ ] Job Story #x : [ description ]
- [ ] Job Story #x : [ description ]
- [ ] Invalidate static JS + CSS browser cache on update
