### ISSUE TITLE
[EPIC] Logging capabilites

### ISSUE THREAD

**Issue by AlexHx8472** [Trustpoint-Project/trustpoint#131]
**Introduction**
The Trustpoint shall support both normal logging as well as (signed) audit logging. Furthermore, the Trustpoint shall support file based logging as well as syslog / rsyslog.

**Acceptance Criteria**
- [ ] Job Story #x : [ description ]
- [ ] Job Story #x : [ description ]

Deprecated?:
- [ ] All important actions and events must be logged
- [x] Log files should be rotated (e.g. daily) to ease backup and browsing
- [ ] Audit log: All successful changes to relevant models (e.g. Device, IssuingCA, Certificate, user management) should be logged with timestamp and actor
- [ ] Different loggers should be configurable (e.g. log files, syslog, log to console...)
- [ ] File logger should have configurable path for log files
