### ISSUE TITLE
[EPIC] Provide a docker container

### ISSUE THREAD

**Issue by AlexHx8472** [TrustPoint-Project/trustpoint#134]
**Introduction**
Using a specific git commit message, a docker container shall be build and uploaded to DockerHub automatically.

**Acceptance Criteria**
- [ ] [ job story ref ] : Include an Apache in the container.
- [ ] [ job story ref ] : On first startup, the container must create and inject a HTTPS server certificate to use.
- [ ] [ job story ref ] : The container must include a setup, in which the reset_db command was executed.
