### ISSUE TITLE
[EPIC] Certificate Lifecycle Management

### ISSUE THREAD

**Issue by Aircoookie** [Trustpoint-Project/trustpoint#143]
**Introduction**
Trustpoint shall implement all necessary functionality to facilitate effective certificate lifecycle management.

**Acceptance Criteria**
- [x] Job Story N/A : Revocation support
- [ ] Job Story #x : CRL / OCSP Endpoints
- [ ] Job Story #x : Automatic Renewal
- [ ] Job Story #x : Short-lived certificates / configurable validity period

The essential aspect of backup is omitted here as it is covered by #130 (unless an automated certificate/credential specific backup is planned in addition to database backups)
